### ISSUE TITLE
Is it possible to include untested files in coverage report using karma-coverage?

### ISSUE THREAD

**Issue by wezleytsai** [istanbuljs/babel-plugin-istanbul#102]
This may be a documentation issue. I see reference to the `--all` flag for `nyc`, but not sure how that fits in with karma config.

I'm using `karma-coverage` and `karma-webpack` with `babel-loader` and this plugin. I can't seem to get untested files to show up in my coverage report.

I have this file as my karma files entry point:
```js
// tests/index.js

const testsContext = require.context('./lib/', true, /\.(js|jsx)$/),
    context = require.context('../lib/', true, /^(?!\/base\/)*\.(js|jsx)$/);

testsContext.keys().forEach(testsContext);
context.keys().forEach(context);
```

`karma-coverage` config setting `includeAllSources` does not seem to do the trick either.

**Comment by wezleytsai** [comment]
Pretty much a duplicate of #29

**Comment by bcoe** [comment]
@wezleytsai there's an approach outlined here for covering all files with `karma`:

https://github.com/istanbuljs/babel-plugin-istanbul/issues/105

I would love to add documentation to the instanbul website, if anyone is so inclined to submit a pull request.
