### ISSUE TITLE
Incompatible support policies of babel-plugin-istanbul and nyc

### ISSUE THREAD

**Issue by rmdm** [istanbuljs/babel-plugin-istanbul#103]
`nyc` [supports node v0.10 (and v0.12)](https://github.com/istanbuljs/nyc/pull/399#issuecomment-248361632) while `babel-plugin-istanbul` [does not](https://github.com/istanbuljs/babel-plugin-istanbul/pull/88). Because of this my build fails on node v0.10 (and v0.12).
```
> NODE_ENV=test nyc _mocha --require babel-register --recursive test
/usr/src/app/node_modules/babel-plugin-istanbul/node_modules/find-up/index.js:2
const path = require('path');
^^^^^
SyntaxError: Use of const in strict mode.
```

.nycrc
```json
{
    "require": [
      "babel-register"
    ],
    "sourceMap": false,
    "instrument": false,
    "reporter": [
        "lcov",
        "text-summary"
    ]
}
```
What is the point of such a divergence and shouldn't it be fixed? What is the recommended workaround? To detect node version and just skip coverage on "bad" ones?

**Comment by bcoe** [comment]
@rmdm over the next few months I intend to continue dropping Node 0.10 and Node 0.12 support across the two major ecosystems I work in (Istanbul, and yargs). The motivation is mainly that 0.10 and 0.12 are now at the end of their lifecycle, and a lot of dependencies that yargs and nyc rely on are starting to force 4+ -- this is making it hard for me as a maintainer to keep libraries up to date, unless I make the move myself.

The Node.js project and npm use `nyc` directly (not `babel-plugin-istanbul`); so I'm probably going to move a few dependencies away from `0.10`, and `0.12` before the core `nyc` module; `babel-plugin-instanbul` was the first module to get this treatment.

The `3.x` branch should continue working on `0.10`/`0.12` and, for major issues, I'm more than happy to back port to this release branch for folks.

**Comment by rmdm** [comment]
It seems the best option for me is to stick to `v3` of the plugin. Thank you for clarification.
