### ISSUE TITLE
Tests fail for function expression exports

### ISSUE THREAD

**Issue by amitrai99** [istanbuljs/babel-plugin-istanbul#106]
We are using React  with `babel-plugin-istanbul` along with Karma and Webpack.
For some reason all the function expression exports fail when running test coverage. Running the tests without coverage does seem to work fine. Is there something that we need to do special to make the coverage to work with function expression exports.

For example,

*This fails:*

```js
export const LinkHelper = () => (
  <a href="/foo">Link</a>
);
```

*This works:*

```js
export function LinkHelper() {
  return (
    <a href="/foo">Link</a>
  );
}
```

*More Info*
Environment : Mac OSX Sierra

**Comment by bcoe** [comment]
@amitrai99 could you provide a minimal failing example -- the underlying issue is that the instrument (https://github.com/istanbuljs/istanbuljs/tree/master/packages/istanbul-lib-instrument) fails to appropriately add line counters for this syntax.

**Comment by bcoe** [comment]
@amitrai99 I have a test for the specific issue you're bumping into:

```js
export const updateName = (name) => {
  return {
    type: 'UPDATE_NAME',
    name
  }
}
export const updateName2 = (name) => {
  return {
    type: 'UPDATE_NAME',
    name
  }
}
export const LinkHelper = () => (
  <a href="/foo">Link</a>
)
```

and have been unable to reproduce the error you're seeing -- I could you provide a link to a minimal failing example, also mind double checking that you're on the newest version of babel-plugin-istanbul.

**Comment by amitrai99** [comment]
@bcoe I am also not able to reproduce this issue on the latest version of React (15.5). 

This might be due to the old version of react (0.14) and babel-core (6.21) or karma (1.6.0) that we were using in older codebase. I am not sure if it';s worth the time trying to fix this issue for older versions of React.

**Comment by bcoe** [comment]
@amitrai99 it might be that React is gradually swapping around some of the babel transforms; I'm glad this isn't happening to you anymore!

I'm going to close, and if it comes up again on newer versions of React, we can dig into it -- thanks for your patience.
