### ISSUE TITLE
html report mostly yellow

### ISSUE THREAD

**Issue by shaunc** [istanbuljs/babel-plugin-istanbul#109]
After a parameter default (though different things trigger in other files, I think), the html report output is all yellow:
![image](https://cloud.githubusercontent.com/assets/193170/26387786/36d68f3a-401e-11e7-8a5b-285fd2003f60.png)

I believe yellow mean "branch not taken". The branch stats for this file seem reasonable -- so I would think this is a bug in the reporter. (I'm using babel-plugin-istanbul 4.1.3, babel 6.24.1, node 7.10.0)

**Comment by bcoe** [comment]
@shaunc I'm unable to reproduce this issue with the following pseudo code, using the `es2015` preset:

```js
export class Class {
  constructor(type, src, terms=[]) {
    const a = 99
    if (true) {
      const b = 101
    }
  }
  foo () {
    const c = 99
  }
}
```

what presets are you using? are you using any other plugins that might potentially conflict with `babel-plugin-istanbul`, e.g., `babel-rewire`?

**Comment by bcoe** [comment]
@shaunc please feel free to re-open this issue if you're continuing to bump into this issue 👍 

I seem to be unable to reproduce with the most up-to-date versions of the instrumenter.
