### ISSUE TITLE
Cannot read property 'fileCoverage' of undefined

### ISSUE THREAD

**Issue by battlesnake** [istanbuljs/babel-plugin-istanbul#118]
I'll file this bug with istanbul-lib-instrument also, however it started happening after I moved from pre-compilation (babel-cli) to on-demand (babel-node/register) which is why I needed to add `babel-plugin-istanbul`.

---

When running:

```istanbul cover _mocha -- --bail --require babel-polyfill --compilers js:babel-register```

Using babel preset `latest` and plugin `istanbul`, I get the following errors (just messages, no stack traces), and they are swallowed somewhere, resulting in the tests subsequently running but no coverage report being generated.

```
Transformation error for /home/mark/ef/oc/qb/marshall/src/main.js ; return original code
Cannot read property 'fileCoverage' of undefined
Transformation error for /home/mark/ef/oc/qb/marshall/src/endpoint/db.js ; return original code
Cannot read property 'fileCoverage' of undefined
Transformation error for /home/mark/ef/oc/qb/marshall/src/config/index.js ; return original code
Cannot read property 'fileCoverage' of undefined
Transformation error for /home/mark/ef/oc/qb/marshall/src/config/db.js ; return original code
Cannot read property 'fileCoverage' of undefined
... et cetera ...
```

I've narrowed it down to `istanbul-lib-instrument/dist/instrumenter.js`, function `instrumentSync`, line `147` (dist), line `100` (source):

```this.fileCoverage = output.fileCoverage;```

I'm using `babel-plugin-istanbul` version:

```
      "version": "4.1.4",
      "integrity": "sha1-GN3oS/POMp/d8/QQP66SFFbY5Yc=",
```

And `istanbul-lib-instrument` version:

```
      "version": "1.7.3",
      "integrity": "sha1-klsjkWPqvdaMxASPUsL6T4mez6c=",
```

I see that `output` is initialised to `{}`, then reassigned in the AST visitor `exit` callback `output = ee.exit(path)`.  So `ee.exit` is returning undefined at some point,

**Comment by athomann** [comment]
I'm getting the same error, were you able to remove the error by going to a previous version?

**Comment by battlesnake** [comment]
I went back to having a separate `build` step in my makefile, running `babel --copy-files --out-dir $(outdir) $(srcdir)`.  Then I have a `test` target (which depends on `build`) that runs `istanbul cover _mocha -- --require babel-polyfill $(outdir)/test`.

Having a separate transpilation step and eliminating babel-node fixed things for me.  I'm still using `babel-plugin-istanbul`.

**Comment by bcoe** [comment]
@battlesnake I would need to look at the specific project that was having issues, but the underlying issue was most likely the include order of `babel-register` vs. `babel-plugin-istanbul`; sounds like you've found a workaround howerver, so closing this specific issue.
