### ISSUE TITLE
cobertura report from karma-coverage missing conditional line details

### ISSUE THREAD

**Issue by kwonoj** [istanbuljs/babel-plugin-istanbul#12]
Replaced configuration from `isparta-loader` (using webpack) to this plugin, successfully generated reports so far but noticed cobertura report missing some details,

``` html
<method name="stateChangeStart"  hits="8"  signature="()V" >
    <lines><line number="undefined"  hits="8" /></lines>
</method>
<method name="stateChangeSuccess"  hits="4"  signature="()V" >
    <lines><line number="undefined"  hits="4" /></lines>
</method>
<method name="stateChangeError"  hits="2"  signature="()V" >
    <lines><line number="undefined"  hits="2" /></lines>
</method>
```

such as above that line numbers are missing, so all conditional details are losing. Is it possibly I missed some sort of configurations?

**Comment by tebari** [comment]
I found a similar issue with lcov reports. It looks like the instrumentation library doesn't include line numbers for branches and maps.

istanbuljs/istanbul-lib-instrument#14

**Comment by gotwarlost** [comment]
This is probably a bug in the new cobertura reporter. I will look into it tonight.

**Comment by ravasthi** [comment]
Hi, any updates on this? The other issue mentioned something about this resulting from a consciously chosen breaking change. Is there something different about how we should be setting up the plugin to get more accurate numbers in Cobertura/lcov reports? Please advise, and thanks for your work on this very useful tool.

**Comment by opichals** [comment]
Adding another snippet. It seems that the class methods contain bogus lines/line/@number values whereas the class/lines/line/@number seem to be fine. Also note the `hits=147` in particular where it looks like the line elements almost match...

```xml
<class name="utils.js"  filename="testUtils.js"  line-rate="0.85"  branch-rate="0.72" >
<methods>
    <method name="strip"  hits="1"  signature="()V" >
        <lines><line number="undefined"  hits="1" /></lines>
    </method>
    <method name="(anonymous_1)"  hits="147"  signature="()V" >
        <lines><line number="undefined"  hits="147" /></lines>
    </method>
    <method name="spy"  hits="1"  signature="()V" >
        <lines><line number="undefined"  hits="1" /></lines>
    </method>
</methods>
<lines>
    <line number="5"  hits="1"  branch="false" />
    <line number="6"  hits="147"  branch="false" />
    <line number="7"  hits="3"  branch="false" />
    <line number="10"  hits="1"  branch="false" />
    <line number="14"  hits="1"  branch="false" />
```

**Comment by bcoe** [comment]
@kwonoj @opichals this should now be fixed in newer versions of istanbul-lib-instrument. Please let me know! If you're continuing to bump into issues we can reopen this.
