### ISSUE TITLE
Is .nycrc file supported?

### ISSUE THREAD

**Issue by redonkulus** [istanbuljs/babel-plugin-istanbul#120]
I'm trying to get coverage working, but seem to be hitting a weird issue. It could be related to my configuration or possibly lack of support for the `.nycrc` file in this plugin.

Given the current `.nycrc` file:
```json
{
  "nyc": {
    "sourceMap": false,
    "instrument": false,
    "exclude": [
      "tests/mock"
    ]
}
```
The `tests/mock` is not excluded when I run:
```
NODE_ENV=test nyc mocha tests/unit --opts ../../mocha.opts
```

However, when I move the configuration from `.nycrc` to the `package.json` file, then it works correctly.

Checking the code, it looks like it assumes that NYC is setting `process.env.NYC_CONFIG` before it runs, but when I `console.log` the config, it doesn't have my "exclude" modification.

Versions:
- nyc@11.0.3
- babel-plugin-istanbul@4.1.4

**Comment by redonkulus** [comment]
Nevermind, I was formatting the .nycrc file incorrectly.

**Comment by phun-ky** [comment]
How should this be formatted? I have the same issue :(

**Comment by NormanPerrin** [comment]
Bit late but instead of
```
{
    "nyc": {
        "sourceMap": false,
        "instrument": false,
        "exclude": [
            "tests/mock"
        ]
    }
}
```

Should be
```
{
    "sourceMap": false,
    "instrument": false,
    "exclude": [
      "tests/mock"
    ]
}
```
