### ISSUE TITLE
Untested Default Parameters Not marked in html report

### ISSUE THREAD

**Issue by bdwain** [istanbuljs/babel-plugin-istanbul#123]
I'm not sure if this issue belongs here or with another istanbul library or with karma coverage, but I've noticed that when the implicit branch created by a default parameter is untested, it does not get marked in the html report (created by the html karma coverage reporter)

I have a function that looks like this

```js
function foo(e){
...
}
```

and it's 100% covered

if i change it to 

```js
function foo(e = {}){
...
}
```
the coverage report correctly says that i'm missing a branch. but when i look at the html report, it is not highlighted in any way. The top of the file says 10/11 branches covered, but it's hard to see what is missing.

**Comment by coreyfarrell** [comment]
I've just tested this under `nyc@13.2.0`, it seems that the html report highlights the default value as a `branch not covered`.  Could you retest with that version, let us know if this is still an issue?

**Comment by bdwain** [comment]
I still see the issue. I am not using nyc, but I am using the latest version of babel-plugin-istanbul and all of the other istanbul and babel related libraries. 

<img width="386" alt="screen shot 2019-01-27 at 11 04 38 pm" src="https://user-images.githubusercontent.com/3982094/51815637-f3ef8200-2287-11e9-97a8-369486d59d87.png">

In that screenshot, the default parameter branch is not covered there, but there's no visual indication.

**Comment by bdwain** [comment]
i tried that but it still looks the same

**Comment by coreyfarrell** [comment]
If you could please create/link a minimum repository to reproduce this issue I can investigate further.

**Comment by fredck** [comment]
Same problem here... very hard to figure out what's missing, but looking at the json report helped spotting the line.

**Comment by coreyfarrell** [comment]
Closing this issue as no reproduction has been provided.
