### ISSUE TITLE
Publish 4.1.5 to npm

### ISSUE THREAD

**Issue by BBB** [istanbuljs/babel-plugin-istanbul#127]
Could you possibly publish `4.1.5` to npm please?

**Comment by digitalmaster** [comment]
Also still waiting for this.. any word?

**Comment by bcoe** [comment]
@BBB @digitalmaster done, sorry about the wait.

For what it's worth, `4.1.5` only updated the instrumenter so on fresh installs of `4.1.3` you should have already been seeing these changes.
