### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by gigaga** [istanbuljs/babel-plugin-istanbul#130]
When I execute my unit-tests with instumentalize code from babel-plugin-istanbul, if my file starts with a comment, it causes the crash below:

`/* ************************************* */
TypeError: Cannot read property '0' of undefined`

**Comment by bcoe** [comment]
@gigaga I'm I'm testing the following code:

```js
/* ************************************* */ 

console.log('hey')
```

With `babel-plugin-istanbul`, and the `es2015` preset, and am unable to reproduce your issue. Could you provide a GitHub repo with an example of this issue happening.

**Comment by gigaga** [comment]
Ok, I am going to do it

**Comment by gigaga** [comment]
Arf! I am not able to reproduce it easily :(
I can reproduce it from my repo. But if I copy paste the whole of files in another place, then I cannot reproduce.
Also, if from my repo, I change my file in any way (simply by adding a space character anywhere for example), I cannot reproduce too :(

Strange behavior...

**Comment by bcoe** [comment]
@gigaga I saw your other bug reproduction, hopefully we'll be able to get to the bottom of both in the not too distant future.

**Comment by coreyfarrell** [comment]
@gigaga I'm going to close this since we're unable to reproduce.  If you're able to reproduce the error again please don't hesitate to comment here or open a new issue.  Keep in mind the `babel-plugin-istanbul@5` uses babel 7, it's possible this issue has been resolved due to updated dependencies.
