### ISSUE TITLE
break 'export default class' 

### ISSUE THREAD

**Issue by roneyrao** [istanbuljs/babel-plugin-istanbul#137]
method 'insertCounter' causes error on source line 'export default class' .
line: `path.insertBefore(T.expressionStatement(increment));`

error: `We don't know what to do with this node type. We were previously a Statement but we can't fit in here?`

thrown in 'babel-traverse/lib/path/modification.js‘, method 'insertBefore'.

**Comment by bcoe** [comment]
@roneyrao try upgrading `istanbul-lib-instrument` to `9.0.1`.

**Comment by bcoe** [comment]
@roneyrao bump, did this work once you upgraded to `9.0.1`?

**Comment by coreyfarrell** [comment]
Closing this as I use `export default class` in my own projects without issue so I assume the issue was fixed.
