### ISSUE TITLE
statementMap doubling production file size

### ISSUE THREAD

**Issue by branpar** [istanbuljs/babel-plugin-istanbul#139]
Hello,

I have noticed that my bundled files keep growing in size and I realized this is because babel-plugin-istanbul is adding `statementMap` coverage sources to my production files.

I have confirmed that if I take out this block from my config my filesize drops by HALF. 
```
"plugins": [
            ["istanbul", {
              "useInlineSourceMaps": false,
              "exclude": [
                "**/modules/internal/*.js",
                "**/vendor/*.js",
                "**/*.tests.js"
              ]
            }]
        ]
```

I tried to follow directions on how to not place sourcemaps (as seen above) but it keeps adding them. Anyone have any insight here? Using babel and webpack as part of this process.

**Comment by branpar** [comment]
As a workaround I have added a check to remove the config section for this if the environment is not test, but this seems like a temporary hack vs a real solution,

**Comment by coreyfarrell** [comment]
It is better to use the babelrc `env` section to restrict babel-plugin-istanbul for testing only.  Example:
```js
{
  "plugins": [
    // other babel plugins here.
  ],
  "env": {
    "test": {
      "plugins": ["babel-plugin-istanbul"]
    }
  }
}
```

Just to be clear babel-plugin-istanbul is expected to significantly increase file size, it also adds significant overhead.  You should be using this plugin for testing only, never for production code.
