### ISSUE TITLE
Reports else path at first line

### ISSUE THREAD

**Issue by danez** [istanbuljs/babel-plugin-istanbul#14]
I think I found an issue in this plugin. Maybe the issue lies in nyc, but i think it is the instrumentation.

Following example:
```js
export default (value) => {
    if (value) {
      let a = 1;
    }
};
```

I have test that covers everything in this example, except it never covers the case where `value` is falsey.

The issue is that on the first line the html report says `else path not taken`. 
<img width="186" alt="bildschirmfoto 2016-07-14 um 18 37 23" src="https://cloud.githubusercontent.com/assets/231804/16847733/bf3d9666-49f2-11e6-8146-dace60cbc96e.png">

The warning is correct, as the test always rans into the `if`, but the warning should at least be at the end of the `if {}` I think.

I digged a little bit more into the generated code and it seems the instrumentation is wrong:

```
...
    branchMap: {
      "1": {
        loc: {
          start: {
            line: 2,
            column: 4
          },
          end: {
            line: 4,
            column: 5
          }
        },
        type: "if",
        locations: [{
          start: {
            line: 2,
            column: 15
          },
          end: {
            line: 4,
            column: 5
          }
        }, {
          start: {
            line: 1,
            column: 0
          },
          end: {
            line: 1,
            column: 0
          }
        }]
      }
    },
...
```

Would it be possible to align the error to the if? Or is there no way to detect were to put it and thats why it is at the beginning? If the code gets more complex it is rather hard to find the correct if.

----
I use : 
nyc: 7.0.0 (sourcemaps and instrumentation disabled)
babel-plugin-istanbul: 1.0.3

commandline: `BABEL_ENV=test nyc mocha test --compilers js:babel-register`

**Comment by bcoe** [comment]
see also: https://github.com/istanbuljs/nyc/issues/316

This will be fixed once we pull in a new version of the instrumenter.

**Comment by bcoe** [comment]
@danez give,

`npm cache clear; npm i nyc@next`  a spin, should have a fix for this.

**Comment by danez** [comment]
Thanks.
