### ISSUE TITLE
Does not cover defaultValue with lodash get method

### ISSUE THREAD

**Issue by orca-orca** [istanbuljs/babel-plugin-istanbul#142]
I am testing an object that is being returned depending on a condition with jest istanbul - 

`const myFunction = params => ({`
`  myNumber: params.numbers ? params.numbers.targetNumber : 0;`
`});`

In this case, I can see that I have 2 branches. 
Currently I am trying to re-write it with lodash get method - 

`const myFunction = response => ({`
 `myNumber: _.get(params, 'numbers.targetNumber', 0), `
`});`

where 0 is a defaultValue, and the issue is, jest instanbul coverage identifies it as 0 branches. 

Is there a way to cover both cases with jest instanbul as lodash lib reduces greatly the amount of code I have to write for complex objects?

**Comment by coreyfarrell** [comment]
This is not possible as your code does not have any branches.  Might be able to accomplish your goal if you use optional chaining / nullish coalescing with a transformation to work on your target platforms.

```js
const myFunction = params => ({
  myNumber: params.numbers?.targetNumber ?? 0
});
```

istanbul does not support detecting the optional chaining `?.` as a branch but it does detect `??` as a branch (the same as `||`).
