### ISSUE TITLE
Wrong "this" context switch for async/await fn

### ISSUE THREAD

**Issue by lifeart** [istanbuljs/babel-plugin-istanbul#144]
from **this** ->

![2018-01-12_12h50_31](https://user-images.githubusercontent.com/1360552/34869401-d84daef8-f797-11e7-80ce-a8961f075078.png)

to **this** ->

![2018-01-12_12h48_33](https://user-images.githubusercontent.com/1360552/34869425-e82bb2fc-f797-11e7-847e-6f821e9aaba2.png)

```
    "babel-plugin-async-to-promises": "^1.0.5",
    "babel-plugin-istanbul": "^4.1.5",
    "babel-polyfill": "6.26.0",
    "babel-core": "6.26.0",
    "babel-preset-es2015": "^6.24.1",
```

Why this7 replaced to this8?

**Comment by coreyfarrell** [comment]
This is not an issue with babel-plugin-istanbul, we do not manipulate `this` variables.  The issue appears to be related to translation from async/await to promises so I'd suggest reporting to the `babel-plugin-async-to-promise` module.
