### ISSUE TITLE
Istanbul ignore hints not working

### ISSUE THREAD

**Issue by pedrocelso** [istanbuljs/babel-plugin-istanbul#15]
Hey guys,

I have some specific code blocks that i want to skip when instrumenting:
<img width="552" alt="bad ignoring" src="https://cloud.githubusercontent.com/assets/2895204/16888830/d540faae-4ab8-11e6-8f9b-8c4e891baf3c.png">

As you can see, this entire code block should be ignored, but unfortunately this is not working, and my coverage report is not as accurate as it used to be.

Let me know if you need any details!

Thanks

**Comment by bcoe** [comment]
<img width="250" alt="screen shot 2016-07-19 at 9 43 22 pm" src="https://cloud.githubusercontent.com/assets/194609/16975307/de1c2204-4df9-11e6-9981-332408235100.png">

@pedrocelso ignore seems to work appropriately for my project, I wonder if there's a difference in our configuration? Here's what my project config looks like:

```json
{ "babel": {
    "presets": [
      "es2015"
    ],
    "env": {
      "test": {
        "plugins": [
          "istanbul"
        ]
      }
    }
  },
  "nyc": {
    "include": [
      "src/**/*.js"
    ],
    "exclude": [
      "src/foo/snuh.js"
    ],
    "require": [
      "babel-core/register"
    ],
    "sourceMap": false,
    "instrument": false
  }
}
```

once we've made sure our configuration is similar, another thing worth checking: is ignore only failing for certain constructs like `async`.

**Comment by r4j4h** [comment]
Is the 'nyc' key read from both package.json and .babelrc? Which has priority?

**Comment by sheeley** [comment]
@r4j4h probably worth asking elsewhere (i'm no expert) but i believe just package.json

**Comment by sheeley** [comment]
sorry, i misread that - my expectation was that it was only read from package.json (based on a resource i can't cite of the top of my head). that's a good question

**Comment by trainerbill** [comment]
seems like ignore if is not working:
![image](https://cloud.githubusercontent.com/assets/3578259/18451262/d088c93a-78fb-11e6-8b3e-eecb24235cca.png)
but ignore next is:
![image](https://cloud.githubusercontent.com/assets/3578259/18451275/dacf3bf4-78fb-11e6-8448-30e7a2990c20.png)

**Comment by john-codeworx** [comment]
Ignore next is also not working here (export):

<img width="685" alt="screen shot 2017-05-31 at 12 54 38 pm" src="https://cloud.githubusercontent.com/assets/26210035/26613910/81012a74-4600-11e7-85de-fc014030aa39.png">

**Comment by bcoe** [comment]
@john-codeworx @pedrocelso this issue is fairly ancient, and we've since made quite a few fixes to babel-plugin-istanbul and istanbul-lib-instrument.

Mind confirming that things are working for you now with newer versions of the library? If you're still bumping into issues, let's create a new ticket 👍
