### ISSUE TITLE
500 Internal Server Error: babel-plugin-istanbul@4.1.6

### ISSUE THREAD

**Issue by Valentin1918** [istanbuljs/babel-plugin-istanbul#153]
If I try to:
npm i babel-plugin-istanbul@4.1.6  --> 500 Internal Server Error: babel-plugin-istanbul@4.1.6
If:
npm i babel-plugin-istanbul@4.1.5 --> it is OK

The same time npm view shows: { latest: '4.1.6', next: '4.1.6' }

Seems latest 4.1.6 is broken.

npm@5.6.0
node@v9.5.0

**Comment by bcoe** [comment]
@Valentin1918 are you still bumping into this issue, I was just able to install from the public npm registry.

**Comment by coreyfarrell** [comment]
v4.1.6 is definitely published correctly to npm and nobody else is reporting this issue.  Unless shown otherwise it seems this was a temporary issue with the npmjs.org site so I'm closing this ticket.
