### ISSUE TITLE
5.0.0 not out on npm?

### ISSUE THREAD

**Issue by wojtekmaj** [istanbuljs/babel-plugin-istanbul#159]
Hey,
just a heads up, you seemed to release 5.0.0 yesterday but it's not actually published on npm. Was that intentional? Sorry if yes!

**Comment by coreyfarrell** [comment]
It is published to npm but under the `next` tag, not `latest`.  You can test it by running `npm install babel-plugin-istanbul@next`.  Keep in mind it has seen very little testing 'in the wild' so if you try it please scrutinize the coverage results and report any issues.
