### ISSUE TITLE
On using `babel-plugin-istanbul` no test coverage is happening.

### ISSUE THREAD

**Issue by sarbbottam** [istanbuljs/babel-plugin-istanbul#168]
Hi there,

Thank you for this plugin. However, on using `babel-plugin-istanbul` no test coverage is happening for my code.

I have created a sample code to reproduce the issue - https://github.com/sarbbottam/test-babel-plugin-istanbul.

Steps to reproduce:

```
$ git clone git@github.com:sarbbottam/test-babel-plugin-istanbul.git
$ cd test-babel-plugin-istanbul
$ npm install
$ npm run test:plugin

```

Actual result:

```
  <Counter />
    ✓ renders (38ms)


  1 passing (49ms)

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
```

Any pointer would be helpful. Please let me know if I can provide more information.

Thanks!

**Comment by coreyfarrell** [comment]
Please see https://istanbul.js.org/docs/tutorials/es2015/.  Two main issues with your repository:
1. Your .babelrc uses plugin `__coverage__`, this should be `istanbul`.
2. You are not disabling the nyc instrument / sourceMap steps.

Fixing these two issues allowed me to see 100% coverage for `counter.js`.  You can add `--instrument=false --source-map=false` to your nyc arguments or you can create an nyc configuration as suggested in the ES2015 tutorial.  It is up to you if you want mocha or nyc to require babel-register.

**Comment by sarbbottam** [comment]
Thank you very much.

> Your .babelrc uses plugin `__coverage__`, this should be `istanbul`.
My bad I missed to update it. It was initially `istanbul`

>You are not disabling the nyc instrument / sourceMap steps.
💯 this has been the primary issue, I missed this step.
