### ISSUE TITLE
Update npm `latest` version

### ISSUE THREAD

**Issue by smalluban** [istanbuljs/babel-plugin-istanbul#178]
`npm info babel-plugin-istanbul` logs:

```bash
'dist-tags': { latest: '5.0.1', next: '5.1.0' },
```

Is `latest` tag should not be updated to `5.1.0` ?

**Comment by coreyfarrell** [comment]
Yes I've just now tagged it to latest.  istanbuljs releases stuff to `next` before releasing to `latest`, unfortunately I received no feedback on the 5.1.0 (or related) patches which updated to babel 7 final release.
