### ISSUE TITLE
Class constructor calls super() out of order

### ISSUE THREAD

**Issue by jlmessenger** [istanbuljs/babel-plugin-istanbul#185]
I'm using `@babel/preset-typescript` to transpile my typescript project to javascript. I had hoped to introduce `babel-plugin-istanbul` when running my test suite to get a coverage report.

I've encountered an issue with class constructors calling `super()` out of order when [typescript parameter properties](http://www.typescriptlang.org/docs/handbook/classes.html#parameter-properties) are used. This causes the following error:
>ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor

I've been able to create a simplified test case:
**src/classes.ts**
```ts
export class First {
	constructor() {
	}
}

export class Second extends First {
	constructor(private readonly value: string) {
		super();
	}
}
```
**.babelrc** (based on [typescript babel starter](https://github.com/Microsoft/TypeScript-Babel-Starter#typescript-babel-starter))
```json
{
	"parserOpts": {
		"plugins": ["typescript"]
	},
	"presets": ["@babel/typescript"],
	"plugins": [
		"@babel/proposal-class-properties",
		"@babel/proposal-object-rest-spread",
		"@babel/transform-modules-commonjs"
	],
	"env": {
		"test": {
			"plugins": ["istanbul"]
		}
	}
}
```
**package.json**:
```json
{
  "name": "ts-nyc-test",
  "version": "0.1.0",
  "scripts": {
    "babel:good": "babel src --out-dir good --extensions \".ts\" --source-maps inline",
    "babel:bad": "BABEL_ENV=test babel src --out-dir bad --extensions \".ts\" --source-maps inline"
  },
  "dependencies": {},
  "devDependencies": {
    "@babel/cli": "^7.2.0",
    "@babel/core": "^7.2.2",
    "@babel/plugin-proposal-class-properties": "^7.2.1",
    "@babel/plugin-proposal-object-rest-spread": "^7.2.0",
    "@babel/plugin-transform-modules-commonjs": "^7.2.0",
    "@babel/preset-typescript": "^7.1.0",
    "@types/mocha": "^5.2.5",
    "@types/node": "^10.12.15",
    "babel-plugin-istanbul": "^5.1.0",
    "mocha": "^5.2.0",
    "nyc": "^13.1.0",
    "typescript": "^3.2.2"
  }
}
```

Compiling _without_ istanbul coverage via `npm run babel:good`
**good/classes.js**
```js
"use strict";
Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.Second = exports.First = void 0;
class First {
  constructor() {}
}
exports.First = First;

class Second extends First {
  constructor(value) {
    super();
    this.value = value;
  }
}
exports.Second = Second;
```

Compiling with istanbul coverage via `npm run babel:bad`
**bad/classes.js**
```js
"use strict";
var cov_1el225kkjv = function () {
  var path = "/src/src/classes.ts",
      hash = "42cdfe6449003fa0779d27df48f661c7a0dbedef",
      Function = function () {}.constructor,
      global = new Function('return this')(),
      gcv = "__coverage__",
      coverageData = {
    path: "/src/src/classes.ts",
    statementMap: {
      "0": {
        start: { line: 8, column: 2 },
        end: { line: 8, column: 10 }
      }
    },
    fnMap: {
      "0": {
        name: "(anonymous_0)",
        decl: {
          start: { line: 2, column: 1 },
          end: { line: 2, column: 2 }
        },
        loc: {
          start: { line: 2, column: 15 },
          end: { line: 3, column: 2 }
        },
        line: 2
      },
      "1": {
        name: "(anonymous_1)",
        decl: {
          start: { line: 7, column: 1 },
          end: { line: 7, column: 2 }
        },
        loc: {
          start: { line: 7, column: 45 },
          end: { line: 9, column: 2 }
        },
        line: 7
      }
    },
    branchMap: {},
    s: { "0": 0 },
    f: { "0": 0, "1": 0 },
    b: {},
    _coverageSchema: "43e27e138ebf9cfc5966b082cf9a028302ed4184"
  },
      coverage = global[gcv] || (global[gcv] = {});

  if (coverage[path] && coverage[path].hash === hash) {
    return coverage[path];
  }

  coverageData.hash = hash;
  return coverage[path] = coverageData;
}();

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.Second = exports.First = void 0;

class First {
  constructor() {
    cov_1el225kkjv.f[0]++;
  }
}
exports.First = First;

class Second extends First {
  constructor(value) {
    this.value = value;
    cov_1el225kkjv.f[1]++;
    cov_1el225kkjv.s[0]++;
    super();
  }
}
exports.Second = Second;
```

**Outcome:**  
When the `babel-plugin-istanbul` plugin is not used, `super()` is correctly called before `this.value`.

In the second case, when the `babel-plugin-istanbul` plugin is added, the `Second` class constructor incorrectly calls `this.value = value;` before `super()` causing the error.

Thank you for any help and support!

**Comment by jlmessenger** [comment]
Per @bcoe this may be an issue in the `istanbul-lib-instrument` package.

I've found a matching issue reported there:
https://github.com/istanbuljs/istanbuljs/issues/237

I'm cross-linking them, so please close which whichever is in the wrong place - Thanks!

**Comment by coreyfarrell** [comment]
@jlmessenger I believe this issue should be fixed by the release of babel 7.5.0, can you confirm that running `npm update` on your repository fixes it for you?

**Comment by coreyfarrell** [comment]
It's been confirmed in the istanbuljs ticket that the updated babel fixes this issue so I'm closing this issue.

**Comment by jlmessenger** [comment]
I was taking a day off yesterday, but confirmed it for both vanilla TS and nyc/istanbul instrumented code today. Thanks for following up @coreyfarrell !
