### ISSUE TITLE
Babel macro for create-react-app

### ISSUE THREAD

**Issue by vijayst** [istanbuljs/babel-plugin-istanbul#188]
I want to use babel-plugin-istanbul with create-react-app v2. CRA has this new thing called babel macros. Is there any plan to write a babel macro. Maybe we can wrap the root component with another component for instrumentation.

```
import istanbul from "babel-macro-istanbul";
export default istanbul(App);  // root component to instrument the whole app
```

Any plans of doing such a thing so that we can use CRA without ejecting. 

It can also have an optional parameter, which can dynamically disable the macro per environment.

```
export default istanbul(App, process.env.NODE_ENV === 'test');
```

**Comment by heyimalex** [comment]
I honestly don't know enough to say for sure, but I don't think it's possible with babel-macros. Istanbul really needs to add instrumentation to everything. For something like `istanbul(App)` we'd only be passed "App". Like... just the word "App". Plugins operate at the ast level, at compile time and not runtime, so the macro wouldn't know what code you actually wanted to instrument just by a name. At best I think you'd have to wrap all of the _actual code_ you want to add instrumentation to. If you just needed to instrument one or two functions shallowly it would be fine, but if you want full coverage you'd need to wrap everything. At that point you're probably better off just using the plugin?

**Comment by vijayst** [comment]
@heyimalex Thanks for clarifying. CRA includes the plugin only for the test command. (react-scripts test). For build and start, they do not include the plugin. I have raised an [issue in the CRA repo](https://github.com/facebook/create-react-app/issues/6191) to include the plugin. But was just checking if we could write a macro which is the new way of doing things in CRA without ejecting.

**Comment by vijayst** [comment]
@heyimalex I think Babel macros are useful for replacing code inline within files. But it does not help with per file processing. So you are right, We can't do a macro here. Hence closing it.
