### ISSUE TITLE
lcov file misses line numbers.

### ISSUE THREAD

**Issue by MrHus** [istanbuljs/babel-plugin-istanbul#20]
When the lcov file is generated it is missing line numbers.

This is what is generated:

``` text
TN:
SF:./src/app.js
FN:,(anonymous_1)
FN:,(anonymous_2)
FN:,(anonymous_3)
FNF:3
FNH:3
FNDA:7,(anonymous_1)
FNDA:7,(anonymous_2)
FNDA:7,(anonymous_3)
DA:11,1
DA:24,7
DA:27,7
DA:29,7
LF:4
LH:4
BRF:0
BRH:0
end_of_record
```

You can see `FN:,(anonymous_1)` which is false because it needs to have a line number before the comma, according to: http://ltp.sourceforge.net/coverage/lcov/geninfo.1.php

My configuration is:

``` JavaScript
'use strict';

module.exports = function(config) {

  config.set({
    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: true,

    // base path, that will be used to resolve files and exclude
    basePath: '../',

    // testing framework to use (jasmine/mocha/qunit/...)
    frameworks: ['jasmine'],

    // list of files / patterns to load in the browser
    files: [
      'test/spec/**/*.js',
      'app/es6/**/*.js',
    ],

    // list of files / patterns to exclude
    exclude: [],

    // web server port
    port: 9002,

    // Start these browsers, currently available:
    // - Chrome
    // - ChromeCanary
    // - Firefox
    // - Opera
    // - Safari (only Mac)
    // - PhantomJS
    // - IE (only Windows)
    browsers: ['PhantomJS'],

    // Which plugins to enable
    plugins: [
      'karma-phantomjs-launcher',
      'karma-jasmine',
      'karma-coverage',
      'karma-junit-reporter',
      'karma-babel-preprocessor',
      'karma-sourcemap-loader',
    ],

    // coverage reporter generates the coverage
    reporters: ['spec', 'coverage', 'junit'],

    preprocessors: {
      'app/**/*.js': ['babel', 'sourcemap'],
      'test/**/*.js': ['babel', 'sourcemap'],
    },
    babelPreprocessor: {
      options: {
        presets: ['es2015'],
        sourceMap: "inline",
        plugins: ['instanbul']
      }
    },
    // optionally, configure the reporter
    coverageReporter: {
      type: 'lcov',
      dir: 'coverage',
      subdir: 'report'
    }
  });
};
```

Did I misconfigure something, or did I stumble unto a bug?

**Comment by gotwarlost** [comment]
I think you are somehow using istanbul v0.x for reporting even if you are using the babel plugin. Please make sure that all istanbul libs are the latest `1.x` versions. This was a breaking change in the coverage format between v0 and v1

**Comment by MrHus** [comment]
In my package.json I added: "istanbul": "1.1.0-alpha.1" just to be sure.

Now when I generate the lcov file I still get the same results.

**Comment by bcoe** [comment]
@MrHus could you share an example of a failing project with us?

**Comment by MrHus** [comment]
@bcoe Yes I'll will do this tomorrow, I'll strip out as much as I can from the project to get it as bare as possible to you can identify the problem.

**Comment by di2pojo** [comment]
Hi, I'm having the same exact problem right now, did you manage to solve this issue?

**Comment by MrHus** [comment]
@di2pojo No I never managed to solve the problem. I'm still hoping for a solution.

**Comment by matteoantoci** [comment]
Same problem here, it's giving me a lot of troubles integrating it with SonarQube, eg:
```
TN:
SF:./src/components/FormElements/utils/validator.js
FN:,(anonymous_0)
FN:,validateField
FN:,validateAllFields
FNF:3
FNH:3
FNDA:74,(anonymous_0)
FNDA:23,validateField
FNDA:2,validateAllFields
DA:5,74
DA:8,23
DA:12,2
DA:15,74
LF:4
LH:4
BRDA:,0,0,1
BRDA:,0,1,22
BRF:2
BRH:2
end_of_record
```

**Comment by Pipeman** [comment]
We have exactly the same issue as reported by @matteoantoci. Were anyone able to solve the issue? I tried to bump to the latest version, but it didn't changed anything.

**Comment by ballwood** [comment]
This is potentially a problem with Karma coverage reporter, I ran into this issue at work the other day. Running tests using the mocha cli and then calling nyc generated a correct lcov report.

**Comment by Chexpir** [comment]
I'd like to keep using Karma coverage reporter. Interestingly, this defect is not open on the karma-coverage project. Is it fair to assume that the bug lies on this codebase? It's pretty annoying that after having all the set up working locally with ES6 you can't integrate it with your sonar systems.

**Comment by nowycheung** [comment]
It is fixed now. Try it.
https://github.com/istanbuljs/istanbuljs/pull/8#issuecomment-287990986

**Comment by Chexpir** [comment]
thanks @nowycheung, I've seen positive feedback on the istanbuljs repo link, but I cannot see the 4.1.0 release in the [npm repository](https://www.npmjs.com/package/babel-plugin-istanbul)

**Comment by bcoe** [comment]
try:

npm install babel-plugin-Istanbul@next

I'll promote to latest once a few folks have tested it out.

**Comment by bcoe** [comment]
this should now be fixed \o/
