### ISSUE TITLE
just one file has coverage data

### ISSUE THREAD

**Issue by 6dingdong6** [istanbuljs/babel-plugin-istanbul#203]
first，I user the command:npm install --save-dev babel-plugin-istanbul
then, I add this in my repo(React native app):
![image](https://user-images.githubusercontent.com/42990001/57289093-51983380-70ed-11e9-9ee8-5515c56bbc6e.png)
finally,I use istanbul-middleware to see the report
![image](https://user-images.githubusercontent.com/42990001/57289909-e4859d80-70ee-11e9-95f6-f3f0801ab49c.png)
however，there is only one file(index.android.js) has coverage data, other .js files have no coverage
![image](https://user-images.githubusercontent.com/42990001/57289925-ecddd880-70ee-11e9-85a1-615bb8579fc0.png)
so, I am wondering: are there some implicit rules in babel istanbul-plugin, which can make this happen?

**Comment by coreyfarrell** [comment]
I cannot help based on a couple of redacted images.  Please provide a minimum reproduction repository showing the issue happening.

Further `istanbul-middleware` uses `istanbul@0.4.x` which is a deprecated / unmaintained predecessor to the current software.  It will cause problems.

**Comment by 6dingdong6** [comment]
https://github.com/6dingdong6/app  this is url, you can download the zip. Thanks! @coreyfarrell

**Comment by coreyfarrell** [comment]
I'm sorry I cannot work with an archive, please push a git repository.

**Comment by 6dingdong6** [comment]
> I'm sorry I cannot work with an archive, please push a git repository.

please try again

**Comment by coreyfarrell** [comment]
Thanks for posting this.  TBH a smaller reproduction is likely to get see someone digging deeper.  I can't test this on my system but one thing I noticed is your `.babelrc` has:
```
        ["istanbul",{
            "include":[
                "./Components/Module/Designer/*/*"
            ]
}],
```
The include setting should be `["Components/Module/Designer/*/*"]` or possibly `["Components/Module/Designer/**"]`.  The current versions of include/exclude matching do not properly handle globs that explicitly start with `./`.

**Comment by 6dingdong6** [comment]
"Components/Module/Designer/*/*" is correct! Thanks! 
But I am still wondering, when I don't use the include setting: ` ["istanbul"]`, the report just shows one file's coverage data; use the include setting:` ["istanbul",{
            "include":[
                "Components/Module/Designer/*/*"
            ]
}],` then the report contains every file's coverage data.
