### ISSUE TITLE
@babel/core transform() not working

### ISSUE THREAD

**Issue by letsgotomars** [istanbuljs/babel-plugin-istanbul#204]
Does this work with babel-core transform()? 

```javascript
const babel = require("@babel/core");
const babelOpts = {
    plugins: ['istanbul'],
};
babel.transform('code();', babelOpts, function(err, result) {
if (err) throw err;
  console.log(result.code);
});
// No .babelrc or babel.config.js files
```

**Comment by coreyfarrell** [comment]
It works with `@babel/core` (babel 7).  `babel-core` is not supported (babel 6).

**Comment by letsgotomars** [comment]
Thanks for the fast response!
I'm using babel 7 and I am getting an error. Here is are my babel and Istanbul packages I have on the project
```
    "@babel/cli": "^7.4.4",
    "@babel/core": "^7.4.4",
    "@babel/preset-env": "^7.4.4",
    "babel-plugin-istanbul": "^5.1.3",
```
Im running on Win 10, with NodeJS v12.1.0


Stack Trace:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Object.relative (path.js:435:5)
    at TestExclude.shouldInstrument (C:\root\node_modules\test-exclude\index.js:99:39)
    at shouldSkip (C:\root\node_modules\babel-plugin-istanbul\lib\index.js:59:21)
    at PluginPass.enter (C:\root\node_modules\babel-plugin-istanbul\lib\index.js:73:15)
    at newFn (C:\root\node_modules\@babel\traverse\lib\visitors.js:193:21)
    at NodePath._call (C:\root\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (C:\root\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (C:\root\node_modules\@babel\traverse\lib\path\context.js:88:12)
    at TraversalContext.visitQueue (C:\root\node_modules\@babel\traverse\lib\context.js:118:16)
```

Thanks again and hope that helps

**Comment by coreyfarrell** [comment]
Oh I see what's going on.  You need to provide the [filename](https://babeljs.io/docs/en/options#filename) option to `babel.transform` (this is automatic when you use `babel.transformFile`).  The filename is required by istanbul.

**Comment by letsgotomars** [comment]
Gotcha. So to clarify there's no support for directly passing code as a string to transform()? i.e. babel.transform('CODE_AS_STRING', opts, ()=>{})

I guess as a workaround I would save the string to a file and then run it through istanbul. Would be a nice feature to have because saving the file to disk is going to cause a performance hit on my application

**Comment by coreyfarrell** [comment]
You don't need to save it to disk, but you do need to give a filename to babel.

```js
const path = require('path');
const babel = require("@babel/core");
const babelOpts = {
    plugins: ['istanbul'],
    filename: path.join(__dirname, 'filename.js')
};
babel.transform('code();', babelOpts, function(err, result) {
if (err) throw err;
  console.log(result.code);
});
// No .babelrc or babel.config.js files
```

**Comment by coreyfarrell** [comment]
Worth noting though some nyc reports may not work if the file is not saved - the HTML report for example.  Other reports may be fine with it.

**Comment by letsgotomars** [comment]
Yes can confirm it works now!!! Just giving it a random filename did the trick.

My application is for instrumented front-end testing so at the end of a test session I am just saving the global '__coverage__' variable to a json file for nyc

Thank you very much for resolving this. It would be nice if this was mentioned somewhere in the docs (even if it's just a small note) but maybe it's just my inexperience with babel

**Comment by coreyfarrell** [comment]
Near the end of the readme under `If you're instrumenting code programatically, you can pass a source map explicitly.` it shows passing the filename option to babel.transform.  This is an advanced use case, most people just use `@babel/register` or CLI.

**Comment by letsgotomars** [comment]
Ah I guess I missed line because it was under the 'Source Maps' section and I just assumed everything under there would be source map specific. Thanks again!
