### ISSUE TITLE
Module build failed: Error: You gave us a visitor for the node type ClassPrivateProperty & Module build failed: TypeError: _iterator[Symbol.iterator] is not a function

### ISSUE THREAD

**Issue by Angelki** [istanbuljs/babel-plugin-istanbul#230]
![image](https://user-images.githubusercontent.com/14013570/68462114-d43daf00-0246-11ea-8cac-0b8b9d578e45.png)

When I add the plugin to `.babelrc`, I get several error.

**Comment by Angelki** [comment]
```json
// .babelrc
{
    "presets": [
        [
            "next/babel",
            {
                "preset-env": {}
            }
        ]
    ],
    "env": {
        "development": {
            "plugins": ["istanbul"]
        }
    },
    "plugins": [
        "transform-decorators-legacy",
        ["transform-define"],
        "inline-import-data-uri"
    ]
}
```

**Comment by coreyfarrell** [comment]
babel-plugin-istanbul v5+ requires babel 7.  To use babel 6 you need to downgrade to babel-plugin-istanbul v4.x.  Note that neither babel 6 nor babel-plugin-istanbul 4 are supported, the last publish to babel-core 6.x was in April 2018 so my advice is to look into upgrading.
