### ISSUE TITLE
babel-plugin-istanbul still uses core-js v.2

### ISSUE THREAD

**Issue by imbroisi** [istanbuljs/babel-plugin-istanbul#240]
When using **babel-plugin-istanbul** in **lerna/yarn workspaces** projects, I am receiving "core-js@<3 is no longer maintained and not recommended for usage due to the number of issues".
I believe **babel-plugin-istanbul** still uses core-js v.2.

**Comment by coreyfarrell** [comment]
babel-plugin-istanbul 4.x is no longer supported or maintained.  This old version uses babel 6 which installs core-js v2.  No version of core-js is installed by the current version of babel-plugin-istanbul.

**Comment by imbroisi** [comment]
Thank you!
