### ISSUE TITLE
Is there any way to look for coverage in one specific folder and not in whole code base in project 

### ISSUE THREAD

**Issue by gauravgandhi15** [istanbuljs/babel-plugin-istanbul#248]

**Comment by coreyfarrell** [comment]
The best way is to set the `include` option, for example:
```js
{
  "plugins": [
    ["babel-plugin-istanbul", {
      "include": ["src/**]
    }]
  ]
}
```

Alternatively you can set include/exclude options to the standard nyc configs, the nyc configs will be loaded if you don't set any options through your babelrc.
