### ISSUE TITLE
coverage report showing wrong results

### ISSUE THREAD

**Issue by AishuGit** [istanbuljs/babel-plugin-istanbul#249]
I updated version for babel-plugin-istanbul from "^5.1.1" to "^6.0.0" .I didn't have any issue with passing of test cases but noticed this is giving me wrong coverage report.

with version ^5.1.1 my coverage report looks like
![5 1 screensshot](https://user-images.githubusercontent.com/63326890/78736431-bddd7180-7912-11ea-9b48-0c266f4aa9cf.PNG)

with version ^6.0.0 my coverage report look like
![6 0 screenshot](https://user-images.githubusercontent.com/63326890/78736461-d3529b80-7912-11ea-831d-9c0374ae80f3.PNG)

there is a difference in coverage for  number of lines covered, classes,branches and etc..so I downgraded my version to 5.1.2 which is working as expected.

I am not sure why 6.0.0 version is not considering many of the things in coverage report?

Thanks!

**Comment by coreyfarrell** [comment]
You have not given any details of your project so it is impossible for me to answer.

**Comment by AishuGit** [comment]
my actual issue is updating to 6.0.0 coverage was not shown for .js files.
but I resolved this by updating .nycrc file extension with ..js.
Thank you foe checking though.
closing this issue.
