### ISSUE TITLE
Setup with karma+webpack+babel-loader doesn't work

### ISSUE THREAD

**Issue by sateffen** [istanbuljs/babel-plugin-istanbul#25]
Hey,

some strange behaviour: I'm using webpack+karma for testing, and the isparta-loader told me to switch. So I tried to switch, but this plugin doesn't work correctly: The babel configuration is ignored, and I get some strange behaviour.

In my karma file I have a webpack configuration:

    webpack: {
        ...
        module: {
            loaders: [
                {
                    test: /\.jsx?$/,
                    loader: 'babel-loader'
                }
            ]
        },
        babel: {
            presets: ['es2015', 'react'],
            plugins: ['transform-object-rest-spread', 'istanbul'],
        },
        ...
    },

This works, and covers ALL my files, even the tests. Ok, so I just want to tell him what to ignore, but if i change my babel configuration to:

    babel: {
        presets: ['es2015', 'react'],
        plugins: ['transform-object-rest-spread', 'istanbul'],
        nyc: {}
    }

It'll find no files anymore. The complete babel process doesn't get anything (your own sourcecode is not called anymore).

Removing the nyc let's webpack and babel do it's job quite fine again. Even configuring valid include and exclude doesn't change anything, no files are found with an nyc configuration.

Configuration in the package-json is a no-go, because our project structure doesn't allow such a configuration (pretty strikt rules here).

I don't know why adding an nyc config there stops the complete process from working, it's just a simple karma + karma-coverage + karma-webpack configuration, without anything special.

**Comment by mandysimon88** [comment]
+ 1

**Comment by mandysimon88** [comment]
+1

**Comment by ernsheong** [comment]
@sateffen Can you post the rest of your karma config, I couldn't get the first part to work

**Comment by sateffen** [comment]
You can take my recent playground (where I'm using this plugin already): [HERE](https://github.com/sateffen/pong-babel-example-2).

This playground configures 3 karma configs: With webpack, rollup and browserify. In the current configuration, without any special config for this plugin, it works. As soon as you add the property `nyc: {}` to any of the babel configurations, it fails.

I retested the part about configuring the plugin directly (writing ['istanbul*, {...}] instead of 'istanbul') and it works.

Is it even supported to configure this plugin in the babel-configuration? Or is this maybe the problem?

**Comment by ernsheong** [comment]
@sateffen thanks a bunch. I've been trying it in `.babelrc` with no luck so far. Maybe it has to go straight into the loader config. I'll try it out soon

**Comment by bcoe** [comment]
@sateffen don't suppose you would be interested in putting some of this information up here:

http://istanbul.js.org/2016/08/02/webpack.html

I've been trying to pull together some material on using Istanbul in various development environments, and don't know enough about webpack to properly speak to it, there's also an open issue here:

https://github.com/istanbuljs/istanbuljs.github.io/issues/7

In the process, would love to know any steps we can take to make things easier.

**Comment by sateffen** [comment]
I think this is no bug in babel-plugin-istanbul, this was just my fail on usage and expectation. The documentation confused me to try to configure this plugin via the *nyc* key in the babel configuration, even though this should not work.

So the main problem is the readmes configuration. Maybe you shouldn't write about other options but the main one: Configure the plugin as plugin, like you have to do, but no other alternatives (so far up). I guess it would help.

**Comment by ernsheong** [comment]
I followed closely the setup in https://github.com/bemusic/bemuse, and ALSO turned Happypack OFF!!! And it finally worked!!
