### ISSUE TITLE
npm publish

### ISSUE THREAD

**Issue by tilgovi** [istanbuljs/babel-plugin-istanbul#3]
I saw that you tagged v1.0.0 but haven't uploaded it to npm.

Apologies if you were just doing some manual testing or something first, but in case it was a simple oversight I thought I'd ping the issue tracker.

This works great in my project if I `npm link` and build it myself and I'm eager to switch!

**Comment by bcoe** [comment]
@gotwarlost ping, don't suppose I could beg borrow or steal the commit bit on npm:

`npm owner add bcoe`

I think we're pretty darn close to being able to land `nyc` too, testing it against `npm/npm` right now, much success -- and very large test suite.

**Comment by gotwarlost** [comment]
sure, I'll add you to all the istanbul modules.

**Comment by bcoe** [comment]
@gotwarlost thank you. I'm having a blast helping to get nyc and Istanbul merged.

**Comment by gotwarlost** [comment]
Added you as owner to:

* istanbul-lib-coverage
* istanbul-lib-instrument
* istanbul-lib-report
* istanbul-reports
* istanbul-lib-source-maps
* istanbul-lib-hook
*babel-plugin-istanbul

I suppose you should now be able to add other owners? Let me know if I missed anything.

**Comment by bcoe** [comment]
@gotwarlost 👍 my testing of nyc has been going quite well, so I might land an alpha pretty soon; but I'm taking note of additional features we will want to add, and additional functionality we'll want to swap out for istanbuljs modules, e.g., source-map functionality.

**Comment by gotwarlost** [comment]
OK, let me start a list of what I think the gaps might be. I'm not very conversant with `nyc` and have little time to go over the code - my family has the ridiculous idea that I should be spending more time with them on holiday rather than on istanbul. Sheer madness :). 

Then we can figure out where this lives, how it is maintained and how we track gaps to closure. We might have to create the "issues repo" sooner rather than later so all these odds and ends can be tracked in one place.

**Comment by rtsao** [comment]
If ya'll want this name you can have it:
https://www.npmjs.com/package/babel-plugin-instrument-istanbul

I only published a fork because I needed a feature

**Comment by bcoe** [comment]
@rtsao @tilgovi I've published v1.0.0 of this module 👍 go ahead and start opening bug reports.

**Comment by tilgovi** [comment]
Thanks!

**Comment by bcoe** [comment]
@rtsao perhaps you could add a deprecation notice, pointing folks towards this plugin?

https://docs.npmjs.com/cli/deprecate
