### ISSUE TITLE
Update to istanbul-lib-coverage to 1.0.0

### ISSUE THREAD

**Issue by bt** [istanbuljs/babel-plugin-istanbul#41]
Once [istanbul-lib-instrument#20](https://github.com/istanbuljs/istanbul-lib-instrument/issues/20) is merged, then we can refer to the new version and that will update `istanbul-lib-coverage` to 1.0.0.

This will add a guard which in turn, will fix `babel-plugin-rewire`.

More information: https://github.com/speedskater/babel-plugin-rewire/issues/148

**Comment by bt** [comment]
Now that [istanbul-lib-instrument#20](https://github.com/istanbuljs/istanbul-lib-instrument/issues/20) has been merged, we can update `istanbul-lib-coverage` to use the new version.

PR incoming!

**Comment by bt** [comment]
@bcoe Any chance of getting this merged? 😄

**Comment by bcoe** [comment]
@bt published in `babel-plugin-istanbul@2.0.1` let me know if this does the trick for you.
