### ISSUE TITLE
HTML report does not hilight missing branch coverage properly with default arguments.

### ISSUE THREAD

**Issue by tuhoojabotti** [istanbuljs/babel-plugin-istanbul#48]
Let's say I have function `door(key, opts = {}) {}`, babel generates the following line inside the function:

```
var opts = arguments.length <= 1 || arguments[1] === undefined ? {} : arguments[1];
```

And obviously branch coverage is not 100 % if there is no tests with default value or value provided. But the LCOV HTML report does not hilight where the branch coverage is missing. It just tells me `97.14% Branches 34/35`

It took me a while to figure out where the missing coverage was hiding, maybe there's another way to find it that I missed, but I think the report should show it.

**Comment by bcoe** [comment]
@tuhoojabotti first off, sorry for the slow reply; I managed to get somewhat buried in issues (something I'e been trying to fix with better organization).

I attempted to create a reproduction of the behavior you were seeing, and it's looking like we might have fixed things in newer versions of Jest/IstanbulJS:

```js

function door(key, opts = {}) {

}
door('key', {batman: 99})
// door('key')
```

<img width="803" alt="screen shot 2017-05-13 at 5 13 07 pm" src="https://cloud.githubusercontent.com/assets/194609/26030176/a2d4a16c-37ff-11e7-979d-2ba664a74bae.png">

I'm closing this issue as fixed; but please feel free to re-open if you're still seeing strange behavior 👍
