### ISSUE TITLE
Exclude option ignored unless in nyc stanza of package.json

### ISSUE THREAD

**Issue by wKovacs64** [istanbuljs/babel-plugin-istanbul#62]
When using `babel-plugin-istanbul`, it appears if the nyc configuration object is included in the `nyc` stanza of `package.json`, everything is fine. But when attempting to use the same options in `.nycrc` or via the command-line, they are ignored (`exclude`, in particular).

Repro examples: https://github.com/wKovacs64/nyc-exclude-test

Side note: in my real projects where I first ran into this, I require `babel-register` with mocha as opposed to nyc. The nyc documentation does it in the nyc configuration, so that's what I used in my reproduction cases, but it doesn't appear to make a difference.

**Comment by tteltrab** [comment]
I just recreated this as well. The `exclude` option in a `.nycrc` file when using this package is ignored, but the files are ignored when the `nyc` configuration is in the `package.json`.

**Comment by bcoe** [comment]
@tteltrab @wKovacs64 I believe there's another issue open on nyc related to this; will dig soon, any help appreciated.

**Comment by 321ckatz123** [comment]
@bcoe the issue is here: https://github.com/istanbuljs/nyc/issues/419.

**Comment by bcoe** [comment]
@321ckatz123 @wKovacs64 I believe we've landed a patch for this, could you give the following a try:

`npm cache clear; npm i nyc@next`

Thanks to @alpersogukpinar for identifying the underlying problem.

**Comment by wKovacs64** [comment]
@bcoe `babel-plugin-istanbul@next (4.0.0)` is working as expected, my exclusion tests pass for command-line, `.nycrc`, and `package.json`. Thanks to all involved!

**Comment by 321ckatz123** [comment]
@bcoe me as well. When can we get this pushed to npm?

**Comment by bcoe** [comment]
@321ckatz123 the module is up, just not on latest yet; try this:

`npm cache clear; npm i babel-plugin-istanbul@next`.

**Comment by 321ckatz123** [comment]
@bcoe, I understand how to get it now. I was more asking when is the next release (which I assume includes this) is going to get pushed?

**Comment by bcoe** [comment]
@wKovacs64 @321ckatz123 this is published to `latest` now 👍
