### ISSUE TITLE
Handle function name inference

### ISSUE THREAD

**Issue by kentcdodds** [istanbuljs/babel-plugin-istanbul#63]
The best way to explain things is via a repo: https://github.com/kentcdodds/issue-babel-plugin-istanbul-fn-name

Here's a copy/paste of the README:
# issue-babel-plugin-istanbul-fn-name

This demonstrates that due to how babel-plugin-istanbul wraps functions, the name of the function is lost

This is a bug and should be fixed.
## Why?

This is causing issues with Jest snapshot testing of React components
## Reproduce:

See the npm scripts, or just run things manually:

```
node test.js
```

Everything passes fine

```
babel-node --plugins istanbul test.js
```

You get two failures. One for the `Foobar` function:

``` js
const Foobar = function() {}
```

And the other for the `Bar` function:

``` js
const Bar = () => {}
```

The istanbul-transformed (`babel --plugins istanbul index.js`) version of these functions looks like this:

``` js
const Bar = (++cov_1788vtfzzh.s[0], () => {
  ++cov_1788vtfzzh.f[1];
});

const Foobar = (++cov_1788vtfzzh.s[2], function () {
  ++cov_1788vtfzzh.f[3];
});
```

This makes it so the JS engine can't do function name inference which causes the issue.

I'm not sure what the babel plugin can do about arrow functions... Can't really give those a name. Definitely possible, but you'd have to do some fancy work to make things work.

But for the function expression that's simple enough.

**Comment by kentcdodds** [comment]
Actually, I realized that in my specific use case, the problem comes because of this behavior:

Basically when we do:

```
const MyComponent = React.createClass({})
```

there's a babel plugin in `babel-preset-react` that will turn that into:

```
const MyComponent = React.createClass({displayName: 'MyComponent'})
```

but what happens is the instrumentation messes things up so the babel plugin can't infer the `displayName`, so what you get is:
```
const MyComponent = (++cov_1788vtfzzh.s[0], React.createClass({}))
```

And Jest snapshots use the `displayName` to in the output. So, until this gets fixed, you can explicitly add the `displayName` yourself and that should work fine as a workaround. Note, this is only a problem with `React.createClass`, function/class components work fine.

**Comment by aaronpowell** [comment]
Another way this manifests itself is through arrow functions for stateless react components. Given a component like so:

```jsx
const MyComponent = () => <h1>Hello World</h1>;
```

Babel will transform this into the following (or at least close enough):

```js
var MyComponent = function MyComponent() { return React.createElement('h1', null, 'Hello World');
```

When you enable the instanbul plugin it will become something like:

```js
var MyComponent = (++cov_1235cas4.s[0], function () { ... });
```

Notice this time that we don't get the function name set, and I'm assuming that's caused by the injection of the coverage step beforehand.

This causes a breaking change in the output JavaScript relative to the input. With anonymous functions in ES2015 the name is infured from the assignment. Running the following in browsers that support ES2015 (Edge, Chrome, FF) will work fine:

```js
const x = () => console.log('a'); console.log(x.name === 'x')
const y = function () {}; console.log(y.name === 'y')
```

**Comment by aaronpowell** [comment]
It's worth noting that there is a workaround for this, if you were to do:

```js
const MyComponent = () => <h1>Hello World</h1>;
MyComponent.displayName = 'MyComponent';
```

The `displayName` property takes priority in React and our tests are passing, but it is just overhead that is needed to be included.

**Comment by goodmorninggoaway** [comment]
+1

**Comment by wyze** [comment]
@kentcdodds I was able to make your tests pass with the following diff to [`istanbuljs/istanbul-lib-instrument`](https://github.com/istanbuljs/istanbul-lib-instrument).

```diff
--- a/src/visitor.js
+++ b/src/visitor.js
@@ -189,6 +189,10 @@ class VisitState {
                 end: { line: n.loc.start.line, column: n.loc.start.column + 1 }
             };
         }
+        if (!n.id) {
+          const decl = path.find(node => node.isVariableDeclarator())
+          n.id = decl.get('id').node;
+        }
         const name = path.node.id ? path.node.id.name : path.node.name;
         const index = this.cov.newFunction(name, dloc, path.node.body.loc);
         const increment = this.increase('f', index, null);
```

And then enable the following plugin as well, [`babel-plugin-transform-es2015-arrow-functions`](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-es2015-arrow-functions). I needed this as I was getting the transform back from babel for `Bar` as:

```js
() => {
  ++cov_js0y0xvmj.f[1];
}
```

I'm not sure that a babel plugin can depend on another plugin, but I could try the above diff on the use case of snapshot testing for React components. Did you have a similar repo setup with snapshot tests that are not working correctly?

**Comment by bcoe** [comment]
@wyze would love a failing test case in `istanbul-lib-instrument`, would definitely accept this patch.

**Comment by bcoe** [comment]
@goodmorninggoaway @kentcdodds @aaronpowell, thanks largely to @wyze's hard work I believe we're  close to a low-touch solution for this issue:

https://github.com/istanbuljs/istanbul-lib-instrument/pull/38

**Comment by bcoe** [comment]
@kentcdodds could I convince you to try out:

`npm cache clear; npm i babel-plugin-istanbul@next`? I believe it has some new logic for handling inferred function names which should solve this issue.

**Comment by kentcdodds** [comment]
Poof!

```
~/Desktop/issue-babel-plugin-istanbul-fn-name (master)
⛄  $ npm run test:babel-node

> issue-babel-plugin-istanbul-fn-name@1.0.0 test:babel-node /Users/kdodds/Desktop/issue-babel-plugin-istanbul-fn-name
> babel-node --plugins istanbul test.js

Passed! 💚
```

**Comment by kentcdodds** [comment]
Thanks so much to everyone who worked on this!
