### ISSUE TITLE
Make `package.json` search conditional

### ISSUE THREAD

**Issue by mathieumg** [istanbuljs/babel-plugin-istanbul#66]
Would you be open to a PR that only does this lookup https://github.com/istanbuljs/babel-plugin-istanbul/blob/9cb75e23e9cfc47044b9617e7f3db966ec3b09d7/src/index.js#L26 when `opts` is not empty?

Currently, both sides of the ternary are run no matter what, so it searches for a `package.json` uselessly. Moreover, it causes issues because I don't use a `package.json` file in my project. A simple refactor to a `if` block solves that issue.

**Comment by bcoe** [comment]
@mathieumg looks like we landed a patch that addressed this at some point? should have updated this ticket, sorry! you're not running into issues any longer?

**Comment by mathieumg** [comment]
Yeah essentially the problem was rather in Jest (see https://github.com/facebook/jest/issues/2016) where it would load `babel-plugin-istanbul` without providing it any options, so the latter would start searching for a package file. Since v18 of Jest, it now provides options when loading the plugin, thus avoiding the codepath where it loads the package file.

So, everything works now but I imagine the better default behaviour would still be to not read the package file if it can't find it:

```js
options = presetOptions || (packageFound && readPackageOptions()) || defaultOptions;
```

Thanks for the follow-up!
