### ISSUE TITLE
add documentation for --all support

### ISSUE THREAD

**Issue by bcoe** [istanbuljs/babel-plugin-istanbul#67]
@motiz88 we should add some docs about how to use `--all`, both in the context of pre-compiling files, and using babel-register for tests.

**Comment by bcoe** [comment]
we should make sure that we document the caveat that `nyc` should `--require` `babel-register`.

**Comment by mstade** [comment]
Hi @bcoe – I found this issue by looking for tips on how to get `--all` to work properly. I was on an outdated version (v8.1.0) and the current version fixed the issue. I'm happy to help with updating the docs, but I'm not sure what you're looking for. I found the docs fairly straight forward with respect to `--all` (or indeed `nyc: { all: true }` which is how I use it.) Any pointers would be very useful!

**Comment by bcoe** [comment]
@mstade going to go ahead and close this; I think you're right, the usage of `--all` with `nyc` is pretty straightforward, and I think for other instrumentation approaches, e.g., (Jest, Karma, gulp), we'd probably need to add documentation on a case by case basis.
