### ISSUE TITLE
Files are erroneously ignored if process.cwd() contains symlinks

### ISSUE THREAD

**Issue by motiz88** [istanbuljs/babel-plugin-istanbul#7]
1) `babel-plugin-istanbul` preprocesses paths with `realpath()` before filtering them with `test-exclude`.
2) `test-exclude` excludes paths that are outside of `process.cwd()`.

When `process.cwd()` includes symlinks, the use of `realpath()` means that _all_ files will appear to be outside of the working directory.

Possible solutions:
##### A) Resolve `process.cwd()` with `realpath()` too
(PR #8 does this)
```javascript
    exclude = testExclude({
      cwd: getRealpath(process.cwd()),
//...
```

Or alternatively:
##### B) Don't use `realpath()` on any files at all
There may, of course, be a good reason to keep using `realpath()` that I'm not aware of.

**Comment by motiz88** [comment]
@bcoe I am seeing a regression to the old behavior due to the use of non-`realpath`-normalized  `NYC_CWD` since fabb602. This issue should probably be reopened.

**Comment by motiz88** [comment]
@bcoe? Anyone?

**Comment by bcoe** [comment]
@motiz88 mind submitting a failing unit-test, I'm not quite sure how to reproduce this failing behavior.

**Comment by motiz88** [comment]
I'll keep thinking about a way to put this in a unit test. Here are the repro steps:

1. Start with a project that is set up to use `babel-plugin-istanbul` and is generating coverage.
2. Create a symlink to the project root, from elsewhere in the file system (Linux `ln` or Windows `mklink`)
3. In a terminal, `cd` to the project via the symlink.
4. Try to generate coverage. All source files will be ignored.
