### ISSUE TITLE
Cannot exclude test/spec files from the coverage report

### ISSUE THREAD

**Issue by nim23** [istanbuljs/babel-plugin-istanbul#71]
I can't seem to get to exclude spec files from the coverage report, with webpack and karma

```javascript
 //.babelrc
{
 ...
  "env": {
     "test": {
        "plugins": [["istanbul", {
        "exclude": "src/**/*.spec.js"
      }]]
   }
 }
....
}
```
My folder structure and test files are structured as below
```
src [folder]
   a.js
   a.spec.js
   components [folder]
       b.js
       b.spec.js
```

My karma configuration looks like below

```javascript
 config.set({
    basePath: './',
    frameworks: ['jasmine'],
    browsers: ['PhantomJS'],
    files: [
      'node_modules/babel-polyfill/dist/polyfill.js',
      'src/**/*.spec.js'
    ],
    preprocessors: {
      'src/**/*.spec.js': ['webpack']
    },
    webpack: {
      module: {
        loaders: [
          {
            test: /\.jsx?$/,
            loader: 'babel',
            exclude: /node_modules/
          }
        ]
      },
    },
    plugins: [
      require('karma-webpack'),
      require('karma-jasmine'),
      require('karma-phantomjs-launcher'),
      require('karma-spec-reporter'),
      require('karma-coverage'),
      require('karma-junit-reporter')
    ],
    reporters: ['junit', 'spec', 'coverage'],
    .....
  })

```

With the above configuration spec file are included in the coverage report.

Any help in pointing me to the right direction is appreciated. Thanks.

**Comment by bcoe** [comment]
@nim23 there was another recent report of this, I believe it's related to enabling `.` folder notation in `micromatch`.

I will dig into this ASAP.

**Comment by nim23** [comment]
Apologies. I dug into this a bit further following your comment and looked into `test-exclude` just to realise that I was passing the exclude option as a string and not an array. 

```javascript
{
 ...
  "env": {
     "test": {
        "plugins": [["istanbul", {
        "exclude": ["src/**/*.spec.js"]
      }]]
   }
 }
```

Passing the exclude option as an array fixed the problem. Closing this issue. Thanks.
