### ISSUE TITLE
file imported as module shows 100% coverage when there is none

### ISSUE THREAD

**Issue by bennewton999** [istanbuljs/babel-plugin-istanbul#85]
I'm new to NYC and Istanbul, so forgive me if I'm missing something obvious here.

## Expected Behavior

Expect the file app.js to show 0% coverage as I have no tests covering it yet. 

## Observed Behavior

When app.js is imported as a module into page1.js, which I do have a test for, app.js shows 100% coverage.

With line 1 of page.js
```----------------|----------|----------|----------|----------|----------------|
File            |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------------|----------|----------|----------|----------|----------------|
All files       |    33.33 |    16.67 |    16.67 |    44.44 |                |
 app            |      100 |      100 |      100 |      100 |                |
  app.js        |      100 |      100 |      100 |      100 |                |
 app/components |    28.57 |    16.67 |    16.67 |     37.5 |                |
  page1.js      |       80 |       50 |       50 |      100 |                |
----------------|----------|----------|----------|----------|----------------|
```
When line 1 of page1.js is commented out, (the import of app.js) The test shows correct coverage.
```----------------|----------|----------|----------|----------|----------------|
File            |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------------|----------|----------|----------|----------|----------------|
All files       |    23.53 |    16.67 |    14.29 |       30 |                |
 app            |        0 |      100 |        0 |        0 |                |
  app.js        |        0 |      100 |        0 |        0 |            4,6 |
 app/components |    28.57 |    16.67 |    16.67 |     37.5 |                |
  page1.js      |       80 |       50 |       50 |      100 |                |
----------------|----------|----------|----------|----------|----------------|
```
## Bonus Points! Code (or Repository) that Reproduces Issue

**app.js** (misc js)

```javascript
import './styles/app.css';

console.log('hello world!!!');

const test = () => console.log('Hello again');
```

**page1.js**
```javascript
import '../app';

console.log('page 2');

const helloWorld = (name = 'Ben') => `Hello World, this is ${name}`;

// export default helloWorld;

const helloWorld2 = (name = 'Ben') => `Hello World, this is not ${name}`;
```
**package.json**
```"nyc": {
    "all": true,
    "sourceMap": false,
    "instrument": false,
    "include": [
      "app/**/*.js"
    ],
    "exclude": [
      "**/*.spec.js",
      "app/dist"
    ],
    "require": [
      "babel-register",
      "ignore-styles"
    ],
    "reporter": [
      "lcov",
      "text",
      "text-summary"
    ],
    "check-coverage": true,
    "cache": false
  }
```

**test.js** (test)
```import { helloWorld, helloWorld2 } from '../app/components/page1.js';

require('chai').should();

describe('helloWorld()', () => {
  it('returns hello world message with Ben as default', () => {
    helloWorld().should.equal('Hello World, this is Ben')
  });

  it('returns hello world message with passed name argument', () => {
    helloWorld('Frank').should.equal('Hello World, this is Frank')
  });
})
```

## Forensic Information

**Operating System:** OSX Yosemite 10.10.5
**Environment Information:** information about your project's environment, see instructions below:

https://gist.github.com/bennewton999/20dc77d6ecb83a94f3cf51df3ba60497

**Comment by bcoe** [comment]
@bennewton999 I _think_ this is expected behavior, because each of the lines inside the module are evaluated when the import takes place; note however, that your branch and function coverage is low, because you have not actually interacted with the module yet:

If you instead change to something like this:

```js
const helloWorld = (name = 'Ben') => {
  console.log('testing')
  `Hello World, this is ${name}`;
}
```

You should see the coverage start to fall.

**Comment by bennewton999** [comment]
@bcoe - Thanks.  First - I fixed the markdown in the comment. I was rushing earlier.

I think I'm missing something.  Why would app.js be at 100% coverage when I have no tests written for the function in app.js.  Shouldn't it remain at 0% untill I have a test covering the function in app.js?

**Comment by bcoe** [comment]
@bennewton999 the act of requiring the module will evaluate the statements at the top level, so I think since you're declaring the functions like so:

`const helloWorld = (name = 'Ben') => `Hello World, this is ${name}`;`

The line evaluates when you import the module, setting `helloWorld` equal to the function, and counting the line as executed. But, the function has not been executed so it's actually the ` % Stmts` and ` % Branches` that will be low.

Try the following:

```js
const helloWorld = (name = 'Ben') => {
  console.log('testing')
  `Hello World, this is ${name}`;
}
```

You should see that the lines are now under 100%?

**Comment by bennewton999** [comment]
@bcoe - Ok, that does change the lines value.  Thanks.  I just have to understand what this is measuring a little clearer.  Just getting started with it.
