### ISSUE TITLE
Not picking up instrumentation generated by istanbul-instrumenter

### ISSUE THREAD

**Issue by the0neWhoKnocks** [istanbuljs/babel-plugin-istanbul#90]
I admit this may not be an issue with your module, but I'm not sure how to proceed. I have this repo https://github.com/the0neWhoKnocks/prototype.testing-legacy-and-es6-code/tree/legacy-refactor and if you run `npm test` you'll see that legacy and ES6 tests (and their sources) bundle & run fine, and coverage appears to be generated correctly.

If you look at the test report in the `.coverage` directory you'll see that the legacy files appear to not have tests written for them, when in fact there are tests, but they were written in ES6 - so `babel-plugin-istanbul` instrumented the test files, but hasn't seen the previously `istanbul-instrumenter` instrumented code.

I may be approaching this whole thing incorrectly but the repo above is as close as I've gotten to mixing a legacy codebase with a newer one. Any suggestions would be greatly appreciated.

**Comment by bcoe** [comment]
@the0neWhoKnocks I'm in the process of triaging tickets (and haven't had time to look at the specific repo you're bumping into issues with); it might be worth also putting a message in our gitter chat, a link to which can be found here:

https://github.com/istanbuljs/nyc

**Comment by the0neWhoKnocks** [comment]
@bcoe You sent me a link to the `nyc` repo. What's the gitter link please?

**Comment by bcoe** [comment]
@the0neWhoKnocks sorry that this was dropped on the floor -- did you end up making any headway getting your tests ported over?

this tutorial might be a good starting point:

https://istanbul.js.org/docs/tutorials/es2015/

**Comment by the0neWhoKnocks** [comment]
Not with Karma. Since we wanted to integrate React I moved our codebase over to Jest. Had to write some middleware but it ended up being easier to deal with than Karma.

**Comment by bcoe** [comment]
@the0neWhoKnocks 👍 jest is using `babel-plugin-istanbul` behind the scenes I believe, I think this approach is great.
