### ISSUE TITLE
Something wrong with "before" hook

### ISSUE THREAD

**Issue by tommiv** [istanbuljs/babel-plugin-istanbul#91]
I'm not sure if title is correct, but:

1. Adding `istanbul` to babel plugins breaks clean tests (without nyc – `NODE_ENV=test mocha`). Unfortunately I can't say what goes wrong exactly. They are just starting to fail with a lot of stacktraces etc., while my app routes returns http/500. It worth to mention that I also use a `rewire` plugin.

2. Running mocha via nyc (`NODE_ENV=test nyc --reporter=lcov --reporter=text _mocha`) says 

>  1)  "before all" hook:
>     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

Then I **get** the coverage table and the info in it seems legit.

For now I split up envs to "test" and "cover". In test env I run clean tests and `istanbul` plugin is not connected here. In "cover" env I use only `istanbul` plugin and run nyc to get coverage table and that strange message about before hook. But this is not so comfortable and requires separate commands and separate app configs.

**Comment by bcoe** [comment]
@tommiv could you share your `nyc` configuration? if you're using `babel-plugin-istanbul` nyc should be a no-op (except for loading reports after the fact).

If the project is open-source, perhaps you could share a branch with this bug?

**Comment by tommiv** [comment]
nyc config is pretty basic

```javascript
  "nyc": {
    "require": [
      "babel-register"
    ],
    "include": [
      "src/resources/**/*.js"
    ],
    "sourceMap": false,
    "instrument": false
  },
```

Unfortunately, the project is not open-sourced.

I will dig deeper into it and will try to attach debugger to check out what's happening.

**Comment by tommiv** [comment]
Sorry, I finally started to investigate this issue and found a floating bug in our code. I'll close this.
