### ISSUE TITLE
Default parameters not covered by branches

### ISSUE THREAD

**Issue by MartinDawson** [istanbuljs/babel-plugin-istanbul#94]
```
const myFunc = (foo = {}) => {
    return foo;
});

describe('myFunc', () => {
    it('should handle default parameter', () => {
        const foo = myFunc(undefined);
        expect(foo).toBe({});
    });
});
```

This says that the branch isn't covered in the command line interface even though it definitely is. Although it doesn't give any syntax highlighting in the report.

If I do:

```
const myFunc = (foo) => {
    foo = foo || {};
    return foo;
});
```

it works fine and generates 100%.

Is this a known bug?

Edit: Just found this is related to https://github.com/istanbuljs/babel-plugin-istanbul/issues/48

**Comment by bcoe** [comment]
Hey @MartinDawson, I've been pretty busy with work the past several weeks sorry for the slow reply -- email was a good way to prod me.

one odd thing that jumps out at me, try:

```js
const myFunc = (foo = {}) => {
    return foo;
};

describe('myFunc', () => {
    it('should handle default parameter', () => {
        const foo = myFunc();
        expect(foo).toBe({});
    });
});
```

You have an extra parenthesis.

If it continues having an issue, it may be an oddity with how babel is configured to transpile code; when I run without transpilation, I get 100% branch, line, and statement coverage.

Could you share the babel configuration that you're using, along with babel-plugin-istanbul?

**Comment by MartinDawson** [comment]
@bcoe I have reproduced this bug for you: https://github.com/MartinDawson/istanbulBug

Clone the repo then:

`npm install`
`npm run coverage`

It might show 100% branch coverage for the first few runs, but if you do it around 4~ times it will drop to 3/4 (75%) branch coverage.

So it looks like an instrumenting problem.

Here's two screenshots of running the coverage one after the other, you can see I changed nothing in the tests and yet it dropped branch coverage.

![untitled](https://cloud.githubusercontent.com/assets/15030491/23798460/b049a670-059c-11e7-8899-7b997244c6a6.png)

![untitled2](https://cloud.githubusercontent.com/assets/15030491/23798462/b16a6c2e-059c-11e7-94b2-29325b2186a6.png)

**Comment by MartinDawson** [comment]
@bcoe I have reproduced this bug for you: https://github.com/MartinDawson/istanbulBug

Clone the repo then:

`npm install`
`npm run coverage`

It might show 100% branch coverage for the first few runs, but if you do it around 4~ times it will drop to 3/4 (75%) branch coverage.

So it looks like an instrumenting problem.
